baseURL = "https://simonagurri.github.io/simonagurri.github.io"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Simona Gurrì"

theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=false

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = false
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

[services]
# Enable Disqus.Disqus.Shortname
  [services.disqus]
    #shortname = 'your-disqus-shortname'
# Google Analytics
  [services.googleAnalytics]
    ID = 'G-FFW4NH8G0B'
