  [[main]]
  name = "Home"
  weight = 100
  url = "/"

  [[main]]
  name = "About"
  weight = 200
  url = "/about"

  [[main]]
  name = "Research Projects"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "Accomplishments"
  weight = 400
  identifier = "accomplishments"

  [[main]]
  name = "Publications"
  weight = 405
  identifier = "publications"
  url = "/publications/"
  parent = "accomplishments"

  [[main]]
  name = "Awards"
  weight = 410
  identifier = "awards"
  url = "/awards/"
  parent = "accomplishments"  

  [[main]]
  name = "Certifications"
  weight = 420
  identifier = "certifications"
  url = "/certifications/"
  parent = "accomplishments"

  [[footer]]
  name = "disclosure"
  weight = 1
  identifier = "disclosure"
  url = "/disclosure/"